FROM java:8-jre
WORKDIR /usr/src

COPY ./target/CricketPlayerFavourite-0.0.1-SNAPSHOT.jar CricketPlayerFavourite-0.0.1-SNAPSHOT.jar
#EXPOSE 8001
ENTRYPOINT ["java","-jar","/usr/src/CricketPlayerFavourite-0.0.1-SNAPSHOT.jar"]